// 운동 데이터 파일
const exerciseData = [
  {
    id: 1,
    title: '푸쉬업',
    type: '상체',
    difficulty: '중급',
    targetMuscle: '가슴',
    mainMuscle: '대흉근',
    secondaryMuscle: '상완삼두근, 삼각근',
    imageSource: require('../../assets/images/Health/push-up.png'),
    gifSource: require('../../assets/images/Health/push-up.gif'),
    exerciseOrder: [
      '1. 엎드린 자세에서 어깨너비 두 배 정도로 두 손을 바닥에 짚고, 발뒤꿈치를 든 상태에서 팔과 무릎을 곧게 편다.',
      '2. 가슴을 바닥 쪽으로 내미는 느낌으로 팔꿈치를 구부려 바닥에 닿기 전까지 몸을 내린다.',
      '3. 겨드랑이에 힘을 주면서 가슴을 모아주는 느낌으로 팔을 편다.',
    ],
    caution: ['1. 손목이 많이 꺾이지 않도록 한다.'],
  },
  {
    id: 2,
    title: '푸쉬업(무릎)',
    type: '상체',
    difficulty: '초급',
    targetMuscle: '가슴',
    mainMuscle: '대흉근',
    secondaryMuscle: '상완삼두근, 삼각근',
    imageSource: require('../../assets/images/Health/kneeing-push-up.png'),
    gifSource: require('../../assets/images/Health/kneeing-push-up.gif'),
    exerciseOrder: [
      '1. 무릎을 대고 엎드린 자세에서 양손을 어깨너비 두 배로 벌리고 발을 꼬아준다.',
      '2. 팔꿈치가 90도가 되도록 몸을 내린다.',
      '3. 겨드랑이에 힘을 주고 가슴을 모아주는 느낌으로 팔꿈치를 밀어주면서 몸을 위로 올린다.',
    ],
    caution: [
      '1. 어깨너비보다 좀 더 넓게 손을 짚고 팔꿈치가 바깥 방향을 향하도록 내려간다.',
    ],
  },
  {
    id: 3,
    title: '풀업',
    type: '상체',
    difficulty: '중급',
    targetMuscle: '등',
    mainMuscle: '광배근',
    secondaryMuscle: '상완이두근',
    imageSource: require('../../assets/images/Health/pull-up.png'),
    gifSource: require('../../assets/images/Health/pull-up.gif'),
    exerciseOrder: [
      '1. 머신 앞에 서서 어깨너비보다 넓게 손잡이를 두 손으로 잡는다.',
      '2. 가슴 윗부분이 바에 닿을 정도로 상체를 끌어올린다.',
      '3. 천천히 시작 자세로 돌아온다.',
    ],
    caution: [
      '1. 허리를 지나치게 뒤로 젖히지 않는다.',
      '2. 팔 힘의 사용을 최소화한다.',
    ],
  },
  {
    id: 4,
    title: '풀업(밴드)',
    type: '상체',
    difficulty: '초급',
    targetMuscle: '등',
    mainMuscle: '광배근',
    secondaryMuscle: '상완이두근',
    imageSource: require('../../assets/images/Health/banding-pull-up.png'),
    gifSource: require('../../assets/images/Health/banding-pull-up.gif'),
    exerciseOrder: [
      '1. 머신 앞에 서서 어깨너비보다 넓게 손잡이를 두 손으로 잡는다.',
      '2. 어시스트 밴드에 올라가서 매달린다.',
      '3. 가슴 윗부분이 바에 닿을 정도로 상체를 끌어올린다.',
      '4. 천천히 시작 자세로 돌아온다.',
    ],
    caution: [
      '1. 허리를 지나치게 뒤로 젖히지 않는다.',
      '2. 팔 힘의 사용을 최소화한다.',
    ],
  },
  {
    id: 5,
    title: '윗몸일으키기',
    type: '상체',
    difficulty: '중급',
    targetMuscle: '복부',
    mainMuscle: '복직근',
    imageSource: require('../../assets/images/Health/sit-ups.png'),
    gifSource: require('../../assets/images/Health/sit-ups.gif'),
    exerciseOrder: [
      '1. 바닥에 누워 무릎을 구부리고 발이 바닥과 떨어지지 않도록 한다.',
      '2. 양손을 귀에 대고 복부에 힘을 주면서 고개를 살짝 든다.',
      '3. 팔꿈치가 무릎에 닿을 때까지 상체를 일으킨다.',
      '4. 천천히 긴장하면서 원위치한다.',
    ],
    caution: ['1. 복근의 힘이 충분하지 못하면 허리에 통증을 유발할 수 있다.'],
  },
  {
    id: 6,
    title: '레그레이즈',
    type: '상체',
    difficulty: '초급',
    targetMuscle: '복부',
    mainMuscle: '복직근 하부',
    imageSource: require('../../assets/images/Health/leg-raise.png'),
    gifSource: require('../../assets/images/Health/leg-raise.gif'),
    exerciseOrder: [
      '1. 벤치에 누워 벤치 윗부분을 두 손으로 잡는다.',
      '2. 다리를 들어올린 후 골반을 가슴 쪽으로 말아 올린다.',
      '3. 저항을 느끼며 다시 원위치한다.',
    ],
    caution: ['1. 다리를 내리는 동작에서 허리가 뜨지 않도록 주의한다.'],
  },
  {
    id: 7,
    title: '레그레이즈(행잉)',
    type: '상체',
    difficulty: '상급',
    targetMuscle: '복부',
    mainMuscle: '복직근 하부',
    secondaryMuscle: '힙 굴곡근',
    imageSource: require('../../assets/images/Health/hanging-leg-raise.png'),
    gifSource: require('../../assets/images/Health/hanging-leg-raise.gif'),
    exerciseOrder: [
      '1. 철봉에 매달려 몸을 펴고 무릎을 약간 구부린다.',
      '2. 무릎을 가슴 쪽으로 끌어당긴다.',
      '3. 천천히 다리를 내린다.',
    ],
    caution: [
      '1. 초보자는 실시하지 않도록 한다.',
      '2. 수축 시 상체가 흔들리지 않도록 주의한다.',
    ],
  },
  {
    id: 8,
    title: '스쿼트',
    type: '하체',
    difficulty: '중급',
    targetMuscle: '허벅지 앞',
    mainMuscle: '대퇴사두근',
    secondaryMuscle: '대둔근, 슬굴곡근',
    imageSource: require('../../assets/images/Health/squat.png'),
    gifSource: require('../../assets/images/Health/squat.gif'),
    exerciseOrder: [
      '1. 선 자세에서 양손을 앞으로 모은다.',
      '2. 어깨너비로 서서 허벅지와 수평이 될 때까지 앉는다.',
      '3. 발뒤꿈치로 민다는 느낌으로 일어선다.',
    ],
    caution: [
      '1. 허리를 곧게 펴고, 척추의 곡선을 유지한다.',
      '2. 무릎이 바깥쪽 또는 안쪽으로 굽히지 않도록 주의한다.',
    ],
  },
  {
    id: 9,
    title: '한 발 스쿼트',
    type: '하체',
    difficulty: '중급',
    targetMuscle: '하체',
    mainMuscle: '대퇴사두근',
    secondaryMuscle: '햄스트링, 엉덩이 근육',
    imageSource: require('../../assets/images/Health/one-leg-squat.png'),
    gifSource: require('../../assets/images/Health/one-leg-squat.gif'),
    exerciseOrder: [
      '1. 벤치나 의자 앞에 발을 골반 너비로 벌리고 선다.',
      '2. 왼발을 바닥에서 들어올리고 발끝을 위로 향하게 한다.',
      '3. 오른쪽 무릎을 천천히 구부리며 몸을 낮춘다.',
      '4. 시작 자세로 돌아온다.',
    ],
    caution: [
      '1. 상체를 곧게 유지한다.',
      '2. 무릎이 발끝을 넘지 않도록 주의한다.',
    ],
  },
  {
    id: 10,
    title: '런지',
    type: '하체',
    difficulty: '중급',
    targetMuscle: '허벅지 앞',
    mainMuscle: '대퇴사두근',
    secondaryMuscle: '대둔근, 슬굴곡근',
    imageSource: require('../../assets/images/Health/lunge.png'),
    gifSource: require('../../assets/images/Health/lunge.gif'),
    exerciseOrder: [
      '1. 두 발을 골반 너비로 벌리고 선다.',
      '2. 오른발을 앞으로 내밀고 왼발 뒤꿈치를 든다.',
      '3. 오른쪽 무릎을 90도로 구부리며 몸을 내린다.',
      '4. 시작 자세로 돌아온다.',
    ],
    caution: [
      '1. 무릎이 발끝을 넘지 않도록 한다.',
      '2. 허리가 앞으로 숙여지지 않도록 주의한다.',
    ],
  },
  {
    id: 11,
    title: '카프레이즈',
    type: '하체',
    difficulty: '초급',
    targetMuscle: '종아리',
    mainMuscle: '비복근',
    secondaryMuscle: '가자미근',
    imageSource: require('../../assets/images/Health/calf-raise.png'),
    gifSource: require('../../assets/images/Health/calf-raise.gif'),
    exerciseOrder: [
      '1. 스텝박스 위에 발끝 1/3 정도 딛고 올라선다.',
      '2. 최대한 높이 발뒤꿈치를 들어올린다.',
      '3. 천천히 발뒤꿈치를 내려준다.',
    ],
    caution: ['1. 운동 중 무릎이 굽혀지지 않도록 한다.'],
  },
  {
    id: 12,
    title: '힙 쓰러스트',
    type: '하체',
    difficulty: '중급',
    targetMuscle: '엉덩이, 고관절',
    mainMuscle: '엉덩이 근육',
    secondaryMuscle: '햄스트링, 대퇴사두근, 척추 기립근, 복근',
    imageSource: require('../../assets/images/Health/hip-thrust.png'),
    gifSource: require('../../assets/images/Health/hip-thrust.gif'),
    exerciseOrder: [
      '1. 바닥에 앉아 등을 벤치나 스텝에 기대고 시작한다.',
      '2. 발은 바닥에 골반 너비로 벌리고 고정한다.',
      '3. 골반을 들어 올려 엉덩이를 위로 밀어 올린다.',
      '4. 천천히 골반을 내리고 반복한다.',
    ],
    caution: [
      '1. 허리를 과도하게 젖히지 않도록 주의한다.',
      '2. 고관절을 제대로 움직이도록 주의한다.',
    ],
  },
];

export default exerciseData;
